/**
 * DEV ONLY. In-memory settings, rules and About services for the fixture
 * harness, so the Settings page can be exercised without the engine. Never
 * imported by production code paths (reached only through `FixtureHarness`).
 *
 * Paths and names are placeholders.
 */
import { tauriFeatures, type FeatureServices } from "../features";
import { validateSettings, type Explanation, type RuleInfo, type Settings } from "../lib/settings";

/** Backend commands these fakes implement (merged into the harness capabilities). */
export const FIXTURE_FEATURE_COMMANDS: readonly string[] = [
  "settings_load",
  "settings_save",
  "settings_export",
  "settings_import",
  "rules_list",
  "rules_reload",
  "rules_open_folder",
  "rules_explain",
  "helper_service_status",
  "about_licenses",
  "updates_check",
  "data_clear",
];

function defaults(): Settings {
  return {
    scan: {
      default_size_mode: "allocated",
      exclude_globs: ["D:\\Backups\\**", "**\\node_modules\\.cache\\**"],
      include_network_drives: false,
      auto_scan_on_launch: true,
      auto_scan_removable: false,
      walker_concurrency: 0,
      show_follow_policy: true,
    },
    live: { usn_enabled: true, update_tick_ms: 1000, auto_rescan_on_journal_loss: true },
    activity: { enabled: false, retention_days: 30, cpu_cap_percent: 2 },
    helper: { mode: "on_demand" },
    cleanup: { default_method: "recycle_bin", large_delete_confirm_bytes: 10 * 1024 ** 3, stale_node_modules_days: 90, stale_installers_days: 60, duplicates_min_bytes: 1024 ** 2 },
    history: { snapshot_interval_hours: 24, retention_days: 90, thin_after_days: 30, min_dir_bytes: 16 * 1024 ** 2 },
    appearance: { theme: "system", color_mode: "category", treemap_style: "cushion", units: "binary", compact_density: false },
    rules: { user_rules_enabled: true, user_rules_dir: null },
    startup: { launch_at_login: false, start_minimized_to_tray: false },
    tray: { enabled: false, low_space_notification: true, low_space_threshold_bytes: 10 * 1024 ** 3 },
    updates: { channel: "stable", auto_download: true },
    privacy: { crash_reports_opt_in: false },
  };
}

const PACKS: readonly [string, number][] = [
  ["windows", 64],
  ["browsers", 38],
  ["dev-tools", 52],
  ["games", 21],
  ["ai-models", 12],
  ["media-apps", 17],
];

function rules(): RuleInfo[] {
  const out: RuleInfo[] = [];
  for (const [pack, n] of PACKS) {
    for (let i = 0; i < n; i++) {
      out.push({
        id: `${pack}.rule-${i}`,
        name: `${pack} rule ${i}`,
        pack,
        source: "builtin",
        category: 6,
        safety: "safe",
        explain: "Regenerated by the app.",
        action: "delete",
        app: null,
        regenerable: true,
        overriddenBy: pack === "dev-tools" && i < 2 ? `mine.override-${i}` : null,
      });
    }
  }
  out.push({ id: "mine.override-0", name: "Keep build cache", pack: "my-rules", source: "user", category: 5, safety: "careful", explain: "Shared build cache.", action: "info_only", app: null, regenerable: false, overriddenBy: null });
  return out;
}

const EXPLANATION: Explanation = {
  path: "C:\\Users\\me\\AppData\\Local\\Temp",
  result: { category: 7, safety: "safe", ruleId: "windows.temp", regenerable: true },
  rule: {
    id: "windows.temp",
    name: "Windows temporary files",
    pack: "windows",
    source: "builtin",
    category: 7,
    safety: "safe",
    explain: "Temporary files that Windows and apps recreate as needed. Files in use are skipped during cleanup.",
    action: "delete",
    app: "Windows",
    regenerable: true,
    overriddenBy: null,
  },
  originPath: null,
  steps: [
    { path: "C:\\Users\\me", ruleId: null, category: 9, safety: "never" },
    { path: "C:\\Users\\me\\AppData\\Local", ruleId: "windows.appdata-local", category: 2, safety: "careful" },
    { path: "C:\\Users\\me\\AppData\\Local\\Temp", ruleId: "windows.temp", category: 7, safety: "safe" },
  ],
  trace: [
    "windows.temp: matched {LOCALAPPDATA}\\Temp (priority 900, built-in)",
    "windows.appdata-local: matched {LOCALAPPDATA} (priority 100), lower priority",
    "user-data.default: fallback, not needed",
  ],
};

/**
 * Feature services with working fakes for Settings; every other group stays
 * on the Tauri implementation (which reports "not available" in a browser).
 *
 * @returns Feature services for the harness.
 */
export function fixtureFeatures(): FeatureServices {
  let stored = defaults();
  const wait = <T>(v: T, ms = 120) => new Promise<T>((r) => setTimeout(() => { r(v); }, ms));
  return {
    ...tauriFeatures,
    settings: {
      ...tauriFeatures.settings,
      loadSettings: () => wait(structuredClone(stored)),
      saveSettings: (s) => {
        const issues = validateSettings(s);
        if (issues.length === 0) stored = structuredClone(s);
        return wait({ settings: structuredClone(stored), issues });
      },
      exportSettings: () => wait(JSON.stringify({ format: "strata-settings", version: 1, settings: stored }, null, 2)),
      importSettings: () => wait({ settings: structuredClone(stored), issues: [] }),
      fetchRules: () => wait(rules()),
      reloadRules: () => wait({ builtin: PACKS.reduce((a, [, n]) => a + n, 0), user: 1, problems: [] }),
      openRulesFolder: () => wait(null),
      explainPath: (path) => wait({ ...EXPLANATION, path }, 200),
      fetchHelperService: () => wait({ installed: false, running: false }),
      fetchLicenses: () =>
        wait([
          { name: "tauri", version: "2.11.5", license: "Apache-2.0 OR MIT", ecosystem: "cargo" as const, repository: null },
          { name: "serde", version: "1.0.228", license: "MIT OR Apache-2.0", ecosystem: "cargo" as const, repository: null },
          { name: "rusqlite", version: "0.37.0", license: "MIT", ecosystem: "cargo" as const, repository: null },
          { name: "react", version: "19.3.0", license: "MIT", ecosystem: "npm" as const, repository: null },
          { name: "zustand", version: "5.0.15", license: "MIT", ecosystem: "npm" as const, repository: null },
        ]),
      checkForUpdates: () => wait({ current: "0.1.0", latest: null, available: false, channel: stored.updates.channel }, 400),
      clearData: () => wait(null),
    },
  };
}
