/**
 * Test doubles for the wave-2 feature services: every call rejects with
 * BackendUnavailableError unless a test overrides it, plus small synthetic
 * fixtures (placeholder paths only).
 */
import { vi } from "vitest";
import type { FeatureServices } from "../features";
import { BackendUnavailableError } from "../lib/backend";
import type { CleanupPlan, QueueEntry } from "../lib/cleanup";
import type { DupeGroup } from "../lib/dupes";
import type { Settings } from "../lib/settings";

type Api = Record<string, (...args: never[]) => unknown>;

function unavailable(group: string): Api {
  return new Proxy(
    {},
    {
      get(_t, name: string) {
        if (name.startsWith("watch")) return () => () => undefined;
        return () => Promise.reject(new BackendUnavailableError(`${group}.${name}`, "not in this test"));
      },
    },
  );
}

/** Partial overrides per API group. */
export type FeatureOverrides = { [K in keyof FeatureServices]?: Partial<FeatureServices[K]> };

/**
 * Builds feature services where only the overridden calls work.
 *
 * @param overrides - Per-group implementations.
 * @returns Feature services.
 */
export function fakeFeatures(overrides: FeatureOverrides = {}): FeatureServices {
  const groups = ["cleanup", "tools", "insights", "dupes", "activity", "history", "settings"] as const;
  const out = {} as Record<string, unknown>;
  for (const g of groups) {
    const base = unavailable(g);
    const o = (overrides[g] ?? {}) as Api;
    out[g] = new Proxy(o, {
      get(t, name: string) {
        return name in t ? t[name] : base[name];
      },
    });
  }
  return out as unknown as FeatureServices;
}

/** A queue entry with synthetic data. */
export function queueEntry(id: number, patch: Partial<QueueEntry> = {}): QueueEntry {
  return {
    id,
    volumeId: "fixture",
    entryId: 100 + id,
    path: `C:\\Users\\me\\AppData\\Local\\Example\\item-${id}`,
    name: `item-${id}`,
    isDir: true,
    bytes: 1024 ** 3 * id,
    safety: "safe",
    category: 6,
    ruleId: "example.cache",
    ruleName: "Example cache",
    explain: "Regenerated by the app.",
    regenerable: true,
    app: "Example",
    addedMs: Date.UTC(2026, 0, 1),
    source: "manual",
    ...patch,
  };
}

/** A plan over the given entries with no warnings. */
export function plan(items: QueueEntry[], patch: Partial<CleanupPlan> = {}): CleanupPlan {
  return {
    planId: 7,
    items,
    totals: [],
    volumes: [{ mountPoint: "C:\\", recycleBin: { state: "available", capacity: 50 * 1024 ** 3, used: 0 }, items: items.length, bytes: items.reduce((a, i) => a + i.bytes, 0) }],
    warnings: [],
    largeDeleteBytes: 10 * 1024 ** 3,
    defaultMethod: "recycle_bin",
    ...patch,
  };
}

/** A duplicate group of `n` copies; copy 0 is the suggested keep. */
export function dupeGroup(id: number, n: number): DupeGroup {
  return {
    id,
    size: 50 * 1024 ** 2,
    wastedBytes: 50 * 1024 ** 2 * (n - 1),
    sameVolume: true,
    keep: { fileId: 0, reason: "oldest", explain: "Oldest copy." },
    files: Array.from({ length: n }, (_, i) => ({
      fileId: i,
      volumeId: "fixture",
      entryId: 1000 + id * 10 + i,
      path: `D:\\Media\\copy-${id}-${i}.mkv`,
      modifiedMs: Date.UTC(2025, 0, 1 + i),
      safety: null,
      inDownloads: i === n - 1,
    })),
  };
}

/** Default settings (mirror of `strata_store::Settings::default`). */
export function defaultSettings(): Settings {
  return {
    scan: {
      default_size_mode: "allocated",
      exclude_globs: [],
      include_network_drives: false,
      auto_scan_on_launch: true,
      auto_scan_removable: false,
      walker_concurrency: 0,
      show_follow_policy: true,
    },
    live: { usn_enabled: true, update_tick_ms: 1000, auto_rescan_on_journal_loss: true },
    activity: { enabled: false, retention_days: 30, cpu_cap_percent: 2 },
    helper: { mode: "on_demand" },
    cleanup: {
      default_method: "recycle_bin",
      large_delete_confirm_bytes: 10 * 1024 ** 3,
      stale_node_modules_days: 90,
      stale_installers_days: 60,
      duplicates_min_bytes: 1024 ** 2,
    },
    history: { snapshot_interval_hours: 24, retention_days: 90, thin_after_days: 30, min_dir_bytes: 16 * 1024 ** 2 },
    appearance: { theme: "system", color_mode: "category", treemap_style: "cushion", units: "binary", compact_density: false },
    rules: { user_rules_enabled: true, user_rules_dir: null },
    startup: { launch_at_login: false, start_minimized_to_tray: false },
    tray: { enabled: false, low_space_notification: true, low_space_threshold_bytes: 10 * 1024 ** 3 },
    updates: { channel: "stable", auto_download: true },
    privacy: { crash_reports_opt_in: false },
  };
}

/** A resolved mock. */
export function resolves<T>(value: T) {
  return vi.fn(() => Promise.resolve(value));
}
